/*
-- Query: SELECT * FROM aus.Etape
LIMIT 0, 1000

-- Date: 2022-02-18 13:53
*/
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (1,'Incorporation d\'ingrédient','Mettre tous les ingrédients sauf le sel dans le pétrisseur',0,1);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (2,'Pétrissage','Pétrir en 1ère vitesse pendant 3 minutes',3,1);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (3,'Pétrissage','Pétrir en 2ème vitesse pendant 3 minutes',3,1);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (4,'Incorporation d\'ingrédient','Ajouter le sel',0,1);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (5,'Pétrissage','Pétrir en 2ème vitesse pendant 3 minutes',3,1);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (6,'Pointage','Pointer la préparation',0,1);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (7,'Façonnage','Façonner la baguette',0,1);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (8,'Repos','Apprêter la baguette pendant 1h30',90,1);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (9,'Cuisson','Enfourner à 250°C pendant 20 minutes',20,1);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (10,'Incorporation d\'ingrédient','Mettre tous les ingrédients dans le pétrisseur',0,2);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (11,'Pétrissage','Pétrir en 1ère vitesse pendant 3 minutes',3,2);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (12,'Pétrissage','Pétrir en 2ème vitesse pendant 3 minutes',3,2);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (13,'Pointage','Pointer la préparation',0,2);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (14,'Façonnage','Façonner les pains',0,2);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (15,'Repos','Apprêter les pains pendant 1h30',90,2);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (16,'Cuisson','Enfourner à 240°C pendant 35 minutes',35,2);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (17,'Incorporation d\'ingrédient','Mettre tous les ingrédients sauf le sel dans le pétrisseur',0,3);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (18,'Pétrissage','Pétrir en 1ère vitesse pendant 3 minutes',3,3);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (19,'Pétrissage','Pétrir en 2ème vitesse pendant 5 minutes',5,3);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (20,'Pointage','Pointer la préparation',0,3);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (21,'Façonnage','Façonner la baguette',0,3);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (22,'Repos','Apprêter les pains pendant 2h',120,3);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (23,'Cuisson','Enfourner à 240°C pendant 35 minutes',35,3);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (24,'Incorporation d\'ingrédient','Mettre tous les ingrédients sauf le sel dans le pétrisseur',0,4);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (25,'Pétrissage','Pétrir en 1ère vitesse pendant 3 minutes',3,4);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (26,'Pétrissage','Pétrir en 2ème vitesse pendant 5 minutes',5,4);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (27,'Pointage','Pointer la préparation',0,4);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (28,'Façonnage','Façonner la préparation',0,4);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (29,'Repos','Apprêter les pains pendant 2h',120,4);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (30,'Cuisson','Enfourner à 240°C pendant 35 minutes',35,4);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (31,'Tranchage','Trancher le pain',0,4);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (32,'Incorporation d\'ingrédient','Mettre tous les ingrédients sauf le sel dans le pétrisseur',0,5);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (33,'Pétrissage','Pétrir en 1ère vitesse pendant 3 minutes',3,5);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (34,'Pétrissage','Pétrir en 2ème vitesse pendant 8 minutes',8,5);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (35,'Pointage','Pointer la préparation',0,5);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (36,'Façonnage','Façonner la préparation',0,5);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (37,'Repos','Apprêter les pains pendant 1h15',75,5);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (38,'Cuisson','Enfourner à 200°C pendant 30 minutes',30,5);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (39,'Démoulage','Démouler immédiatement',0,5);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (40,'Incorporation d\'ingrédient','Mettre tous les ingrédients sauf le beurre dans le pétrisseur',0,6);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (41,'Pétrissage','Pétrir en 1ère vitesse pendant 3 minutes',3,6);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (42,'Pétrissage','Pétrir en 2ème vitesse pendant 6 minutes',6,6);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (43,'Incorporation d\'ingrédient','Ajouter le beurre',0,6);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (44,'Pétrissage','Pétrir en 2ème vitesse pendant 6 minutes',6,6);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (45,'Pointage','Pointer la préparation',0,6);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (46,'Façonnage','Façonner la préparation',0,6);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (47,'Repos','Apprêter les pains pendant 1h30',90,6);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (48,'Cuisson','Enfourner à 180°C pendant 15 minutes',15,6);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (49,'Préparation','Torréfier les graines la veille15 minutes à 150°C',15,7);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (50,'Pétrissage','Pétrir en 1ère vitesse pendant 4 minutes',4,7);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (51,'Pétrissage','Pétrir en 2ème vitesse pendant 4 minutes',4,7);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (52,'Préparation','Ajouter les graines',0,7);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (53,'Pétrissage','Pétrir en 2ème vitesse pendant 2 minutes',2,7);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (54,'Pointage','Pointer la préparation',0,7);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (55,'Façonnage','Façonner la préparation',0,7);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (56,'Repos','Apprêter les pains pendant 1h30',90,7);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (57,'Cuisson','Enfourner à 250°C pendant 20 minutes',20,7);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (58,'Incorporation d\'ingrédient','Mettre tous les ingrédients sauf le beurre dans le pétrisseur',0,8);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (59,'Pétrissage','Pétrir en 1ère vitesse pendant 3 minutes',3,8);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (60,'Pétrissage','Pétrir en 2ème vitesse pendant 6 minutes',6,8);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (61,'Pétrissage','Pétrir en 3ème vitesse pendant 6 minutes',6,8);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (62,'Pointage','Pointer la préparation',0,8);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (63,'Manipulation','Former les croissants',0,8);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (64,'Détaillage','Détailler les croissants',0,8);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (65,'Repos','Apprêter les pains pendant 2h30',150,8);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (66,'Cuisson','Enfourner à 180°C pendant 12 minutes',12,8);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (67,'Dorure','Dorer avec le jaune d\'œuf',0,8);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (68,'Incorporation d\'ingrédient','Mettre tous les ingrédients sauf le beurre dans le pétrisseur',0,9);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (69,'Pétrissage','Pétrir en 1ère vitesse pendant 3 minutes',3,9);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (70,'Pétrissage','Pétrir en 2ème vitesse pendant 6 minutes',6,9);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (71,'Pétrissage','Pétrir en 3ème vitesse pendant 6 minutes',6,9);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (72,'Pointage','Pointer la préparation',0,9);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (73,'Manipulation','Former les pains',0,9);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (74,'Préparation','Fourrer avec la barre de chocolat',0,9);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (75,'Détaillage','Détailler les pains',0,9);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (76,'Repos','Apprêter les pains pendant 2h30',150,9);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (77,'Cuisson','Enfourner à 180°C pendant 12 minutes',12,9);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (78,'Dorure','Dorer avec le jaune d\'œuf',0,9);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (79,'Incorporation d\'ingrédient','Mettre tous les ingrédients sauf le beurre dans le pétrisseur',0,10);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (80,'Pétrissage','Pétrir en 1ère vitesse pendant 3 minutes',3,10);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (81,'Pétrissage','Pétrir en 2ème vitesse pendant 6 minutes',6,10);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (82,'Incorporation d\'ingrédient','Ajouter le beurre',0,10);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (83,'Pétrissage','Pétrir en 2ème vitesse pendant 6 minutes',6,10);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (84,'Pointage','Pointer la préparation',0,10);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (85,'Manipulation','Former les pains',0,10);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (86,'Détaillage','Détailler les pains',0,10);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (87,'Repos','Apprêter les pains pendant 1h15',75,10);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (88,'Cuisson','Enfourner à 180°C pendant 12 minutes',12,10);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (89,'Préparation','Délayer la levure dans le lait tiédi',0,11);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (90,'Préparation','Dans un saladier, verser la farine en puits, ajouter le beurre coupé et malaxer.',0,11);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (91,'Préparation','Incorporer le sucre, les œufs, le sel et la levure délayée',0,11);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (92,'Préparation','Travailler la pâte et former une boule',0,11);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (93,'Préparation','Laisser reposer 2h',120,11);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (94,'Préparation','Verser la préparation dans un moule à tarte et ajouter du beurre coupé sur le dessus',0,11);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (95,'Cuisson','Enfourner pour 20 minutes de cuissons à 210°C',20,11);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (96,'Préparation','Couper la pâte en portion de 100gr',0,12);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (97,'Préparation','Etaler la pâte en rectangle de 15x15cm',0,12);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (98,'Préparation','Mélanger la crème fraîche, la ciboulette et l\'ail. Saler et poivrer',0,12);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (99,'Préparation','Ajouter la préparation sur la pâte',0,12);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (100,'Préparation','Y déposer des pommes de terre en lamelle',0,12);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (101,'Préparation','Ajouter des lardons, du gruyère, une pincée de sel',0,12);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (102,'Préparation','Couvrir la préparation avec l\'autre moitié de la pâte',0,12);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (103,'Préparation','Souder les extérmités et disposer les pâtons sur une plaque de cuisson',0,12);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (104,'Préparation','Creuser le dessus des pâtons pour créer une cheminée',0,12);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (105,'Cuisson','Enfourner à 250°C pendant 10 minutes',10,12);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (106,'Préparation','Blanchir les jaunes et le sucre',0,13);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (107,'Préparation','Mélanger la farine et le beurre',0,13);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (108,'Préparation','Incorporer les jaunes+sucre au mélange',0,13);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (109,'Préparation','Disposer la pâte dans une moule rond',0,13);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (110,'Cuisson','Cuire la pâte à 180°C pendant 20 minutes',20,13);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (111,'Préparation','Bouillir le lait avec le sucre vanillé',0,13);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (112,'Préparation','Ajouter un jaune d\'œuf et le sucre et mélanger vigoureusement',0,13);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (113,'Préparation','Oter la préparation à ébumllition et verser la crème sur le fond de tarte',0,13);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (114,'Préparation','Ajouter sur le dessus les fraises coupées en 2',0,13);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (115,'Préparation','Mélanger le beurre, l\'eau et le sucre dans une casserole',0,14);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (116,'Préparation','Hors du feu, ajouter la farine et mélanger',0,14);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (117,'Préparation','Remettre la préparation sur le feu 2 minutes pour l\'assécher',2,14);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (118,'Préparation','Ajouter les jaunes d\'œufs un à un hors du feu et mélanger',0,14);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (119,'Préparation','Ajouter cette préparation dans une poche à douille',0,14);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (120,'Préparation','Former une couronne sur du papier sulfurisé',0,14);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (121,'Cuisson','Mettre au four 1h à 180°C',60,14);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (122,'Préparation','Blanchir les jaunes et le sucre',0,14);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (123,'Préparation','Ajouter le lait bouillant, la maizena et fouetter sur le feu pendant 2 minutes',0,14);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (124,'Préparation','Ajouter le beurre hors du feu en fouettant',0,14);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (125,'Repos','Mettre au frais la crème 2h',120,14);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (126,'Préparation','Découper le tiers supérieur de la couronne',0,14);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (127,'Préparation','Remplir la couronne avec la crème',0,14);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (128,'Préparation','Recouvrir la partie inférieure avec la couronne supérieure',0,14);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (129,'Préparation','Découper la demi-baguette en 2',0,15);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (130,'Préparation','Beurrer les deux cotés du pain',0,15);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (131,'Préparation','Ajouter la tranche de jambon blanc',0,15);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (132,'Préparation','Découper la demi-baguette en 2',0,16);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (133,'Préparation','Beurrer les deux cotés du pain',0,16);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (134,'Préparation','Ajouter la tranche de jambon blanc',0,16);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (135,'Préparation','Ajouter l\'emmental sur le jambon',0,16);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (136,'Cuisson','Cuire un œuf pendant 9 minutes dans l\'eau bouillante',9,17);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (137,'Préparation','Découper la demi-baguette en 2',0,17);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (138,'Préparation','Etaler la mayonnaise sur le pain',0,17);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (139,'Préparation','Ajouter les tomates coupées en tranches',0,17);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (140,'Préparation','Raper les carottes et les déposer dans le pain',0,17);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (141,'Préparation','Ajouter la feuille de salade',0,17);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (142,'Préparation','Couper en tranche l\'œuf dur et l\'ajouter à la préparation',0,17);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (143,'Préparation','Ajouter la tranche de poulet',0,17);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (144,'Préparation','Couper en deux le pain à panini',0,18);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (145,'Préparation','Beurrer le pain',0,18);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (146,'Préparation','Ajouter le jambon et le fromage',0,18);
INSERT INTO `` (`ID_Etape`,`libelle`,`description`,`temps`,`ID_Recette`) VALUES (147,'Préparation','Toaster pendant 2 minutes',2,18);
