/*
-- Query: SELECT * FROM aus.Ingredients
LIMIT 0, 1000

-- Date: 2022-02-18 13:54
*/
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (1,'Farine courante','gr',185,1);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (2,'Eau','ml',115,1);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (3,'Levure','gr',2,1);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (4,'Pâte fermentée','gr',46,1);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (5,'Sel','gr',3,1);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (6,'Farine courante','gr',183,2);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (7,'Eau','ml',147,2);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (8,'Levure','gr',2,2);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (9,'Pâte fermentée','gr',37,2);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (10,'Sel','gr',3,2);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (11,'Sons fins','gr',28,2);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (12,'Farine courante','gr',171,3);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (13,'Farine de seigle','gr',19,3);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (14,'Eau','ml',130,3);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (15,'Sel','gr',3,3);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (16,'Levure','gr',1,3);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (17,'Pâte fermentée','gr',76,3);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (18,'Farine courante','gr',171,4);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (19,'Farine de seigle','gr',19,4);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (20,'Eau','ml',130,4);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (21,'Sel','gr',3,4);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (22,'levure','gr',1,4);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (23,'Pâte fermentée','gr',76,4);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (24,'Farine courante','gr',83,5);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (25,'Farine Gruau','gr',83,5);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (26,'Eau','ml',100,5);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (27,'Sel','gr',3,5);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (28,'Levure','gr',5,5);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (29,'Poudre de lait','gr',5,5);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (30,'Sucre','gr',5,5);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (31,'Beurre','gr',10,5);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (32,'Pâte fermentée viennoise','gr',39,5);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (33,'Farine T45','gr',24,6);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (34,'Eau','ml',12,6);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (35,'Jaunes d\'oeuf','gr',4,6);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (36,'Sel','gr',1,6);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (37,'levure','gr',1,6);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (38,'Poudre de lait','gr',1,6);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (39,'Sucre','gr',2,6);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (40,'Pâte fermentée viennoise','gr',5,6);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (41,'Beurre','gr',3,6);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (42,'Farine courante','gr',26,7);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (43,'Eau','ml',16,7);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (44,'Sel','gr',1,7);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (45,'Levure','gr',1,7);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (46,'Pâte fermentée','gr',7,7);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (47,'Céréales','gr',10,7);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (48,'Farine T45','gr',4,8);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (49,'Farine de tradition','gr',4,8);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (50,'Eau','ml',3,8);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (51,'Jaunes d\'oeuf','pcs',1,8);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (52,'Sel','gr',1,8);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (53,'Levure','gr',1,8);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (54,'Poudre de lait','gr',1,8);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (55,'Sucre','gr',1,8);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (56,'beurre','gr',1,8);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (57,'Pâte fermentée viennoise','gr',2,8);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (58,'Farine T45','gr',4,9);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (59,'Farine de tradition','gr',4,9);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (60,'Eau','ml',3,9);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (61,'Jaunes d\'oeuf','pcs',1,9);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (62,'Sel','gr',1,9);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (63,'Levure','gr',1,9);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (64,'Poudre de lait','gr',1,9);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (65,'Sucre','gr',1,9);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (66,'Beurre','gr',1,9);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (67,'Pâte fermentée viennoise','gr',2,9);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (68,'Barre de chocolat','gr',1,9);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (69,'Farine T45','gr',50,10);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (70,'Eau','ml',30,10);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (71,'Sel','gr',1,10);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (72,'Levure','gr',2,10);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (73,'Poudre de lait','gr',3,10);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (74,'Sucre','gr',6,10);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (75,'Pâte fermentée viennoise','gr',10,10);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (76,'Beurre','gr',12,10);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (77,'Farine','gr',400,11);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (78,'Sucre','gr',30,11);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (79,'Beurre','gr',280,11);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (80,'Lait','ml',280,11);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (81,'Levure','gr',20,11);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (82,'Sucre','gr',30,11);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (83,'Sel','gr',5,11);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (84,'Jaunes d\'oeuf','pcs',2,11);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (85,'Pâte','gr',100,12);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (86,'Pomme de terre','gr',25,12);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (87,'Lardons','gr',30,12);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (88,'Crème fraîche épaisse','gr',15,12);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (89,'Gruyère rapé','gr',25,12);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (90,'Ciboulette','cs',1,12);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (91,'Sel','cs',1,12);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (92,'Poivre','cs',1,12);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (93,'Ail en poudre','cs',1,12);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (94,'Lait','ml',250,13);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (95,'Farine','gr',30,13);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (96,'Sucre','gr',40,13);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (97,'Sucre vanillé','gr',20,13);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (98,'Fraise','gr',500,13);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (99,'Jaunes d\'oeuf','pcs',1,13);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (100,'Farine','gr',75,14);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (101,'Beurre','gr',40,14);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (102,'Jaunes d\'oeuf','pcs',3,14);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (103,'Sucre','gr',50,14);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (104,'Sel','gr',5,14);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (105,'Lait','ml',250,14);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (106,'Beurre','gr',150,14);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (107,'Amandes effilées','gr',20,14);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (108,'Maizena','gr',10,14);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (109,'Baguette','pcs',1,15);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (110,'Beurre','gr',7,15);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (111,'Jambon blanc','gr',50,15);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (112,'Baguette','pcs',1,16);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (113,'Beurre','gr',7,16);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (114,'Jambon blanc','gr',50,16);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (115,'Emmental','gr',20,16);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (116,'Baguette','pcs',1,17);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (117,'Blanc de poulet','gr',50,17);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (118,'Tomate','pcs',1,17);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (119,'Carotte','pcs',1,17);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (120,'Feuille de salade','pcs',1,17);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (121,'Oeuf','pcs',1,17);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (122,'Mayonnaise','gr',20,17);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (123,'Pain à panini','pcs',1,18);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (124,'Jambon blanc','gr',50,18);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (125,'Emmental','gr',100,18);
INSERT INTO `` (`ID_Ingredients`,`libelle`,`mesure`,`quantite`,`ID_Recette`) VALUES (126,'Beurre','gr',5,18);
